### ISSUE TITLE
Switch CI to use ruff instead of black+pylint

### ISSUE THREAD

**Issue by thorwhalen** [cosmograph-org/py_cosmograph#28]
Switching from Pylint + Black to Ruff in your CI setup involves replacing the format-source-code and pylint-validation actions with a Ruff-based action that performs both linting and (optionally) formatting. Here’s how you can modify your current setup:

Updated CI Configuration

```
- name: Install Dependencies
  uses: i2mint/isee/actions/install-packages@master
  with:
    pypi-packages: 'ruff'

- name: Ruff Lint and Format
  shell: bash
  run: |
    # Run Ruff for linting
    ruff check ${{ env.PROJECT_NAME }} --ignore tests,examples,scrap

    # Run Ruff for formatting (optional, only needed if you want Ruff to format instead of Black)
    ruff check ${{ env.PROJECT_NAME }} --fix --select F --line-length=88
```

Explanation of Changes:
	1.	Replace Black with Ruff for Formatting:
	•	Ruff’s --fix flag applies formatting rules. This removes the need for a separate Black step.
	•	The --line-length=88 flag ensures formatting respects the same line length as Black.
	2.	Replace Pylint with Ruff for Linting:
	•	The ruff check command performs linting.
	•	Use --ignore to exclude directories like tests, examples, and scrap, similar to Pylint’s --ignore.
	3.	Enable Specific Linting Rules:
	•	Use --select or --extend-select flags to enable specific rules that align with Pylint’s configuration. Ruff provides extensive rule coverage, but it may not support every Pylint rule. If you relied on custom Pylint rules, verify Ruff’s documentation for equivalent options.
	•	Example: For docstring-related checks, include rules like D.

Ruff Configuration (Optional)

To maintain consistency across environments, consider adding a pyproject.toml file for Ruff configuration. Example:

```
[tool.ruff]
line-length = 88
ignore = ["E501"]  # Example: Ignore long-line warnings
select = ["E", "F", "B", "D"]  # Enable Black, PEP8, and docstring checks
exclude = ["tests", "examples", "scrap"]
fix = true  # Automatically apply fixes for formatting
```

This removes the need to specify many CLI options and ensures consistent behavior locally and in CI.

Why Use Ruff for Both?
	•	Unified Tooling: Ruff handles both linting and formatting, reducing dependencies and simplifying the workflow.
	•	Performance: Ruff is significantly faster than Pylint and Black, making it ideal for CI pipelines.

Next Steps:
	1.	Test the new setup locally to ensure Ruff’s rules and fixes align with your expectations.
	2.	Verify that Ruff provides adequate coverage for any custom Pylint checks you relied on. If not, consider keeping Pylint for specific validations.
	3.	Remove redundant steps (like Black) if Ruff satisfies both formatting and linting requirements.

See [this AI chat](https://chatgpt.com/share/6793bffa-1864-8013-a21e-56096ec47b3f)
